-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 10:27:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveidor` (
  `proveidor_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `carrer` VARCHAR(128) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `pis` VARCHAR(10) NOT NULL,
  `porta` VARCHAR(10) NOT NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `fax` VARCHAR(20) NULL,
  `nif` VARCHAR(20) NOT NULL,
  `recomanat_por` INT NULL,
  PRIMARY KEY (`proveidor_id`),
  UNIQUE INDEX `nif_UNIQUE` (`nif` ASC) VISIBLE,
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `marca_id` INT NOT NULL AUTO_INCREMENT,
  `marca_nom` VARCHAR(45) NOT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`marca_id`),
  UNIQUE INDEX `marca_nom_UNIQUE` (`marca_nom` ASC) VISIBLE,
  INDEX `fk_marca_proveidor1_idx` (`proveidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_marca_proveidor1`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `mydb`.`proveidor` (`proveidor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `carrer` VARCHAR(128) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `pis` VARCHAR(10) NULL,
  `porta` VARCHAR(10) NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo_eletronic` VARCHAR(128) NOT NULL,
  `data_registre` DATETIME NOT NULL,
  `recomanat_client_id` INT NULL,
  PRIMARY KEY (`client_id`),
  INDEX `fk_client_client1_idx` (`recomanat_client_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_client1`
    FOREIGN KEY (`recomanat_client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empleat` (
  `empleat_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `carrer` VARCHAR(128) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `pis` VARCHAR(10) NULL,
  `porta` VARCHAR(10) NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `correo_eletronic` VARCHAR(128) NOT NULL,
  `data_registre` DATETIME NOT NULL,
  PRIMARY KEY (`empleat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ulleres` (
  `ulleres_id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT NOT NULL,
  `marca_id` INT NOT NULL,
  `graduacio_i` FLOAT NOT NULL,
  `graduacio_d` FLOAT NOT NULL,
  `muntura_id` INT NOT NULL,
  `color_muntura` VARCHAR(45) NULL,
  `tipo_muntura` ENUM('flotant', 'pasta', 'metàllica') NULL,
  `color_vidre_i` VARCHAR(45) NULL,
  `color_vidre_d` VARCHAR(45) NULL,
  `empleat_id` INT NOT NULL,
  PRIMARY KEY (`ulleres_id`),
  INDEX `marca_id_idx` (`marca_id` ASC) VISIBLE,
  INDEX `fk_ulleres_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_ulleres_empleat1_idx` (`empleat_id` ASC) VISIBLE,
  CONSTRAINT `marca_id`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`marca_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ulleres_empleat1`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `mydb`.`empleat` (`empleat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
