-- MySQL Script generated by MySQL Workbench
-- Tue Sep 20 12:36:02 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `pizzeria` ;

-- -----------------------------------------------------
-- Table `pizzeria`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`marca` (
  `marca_id` INT NOT NULL AUTO_INCREMENT,
  `marca_nom` VARCHAR(45) NOT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`marca_id`),
  UNIQUE INDEX `marca_nom_UNIQUE` (`marca_nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`client` (
  `client_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `cognoms` VARCHAR(100) NOT NULL,
  `adreca` VARCHAR(128) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`client_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`botiga` (
  `botiga_id` INT NOT NULL AUTO_INCREMENT,
  `adreca` VARCHAR(128) NOT NULL,
  `codi_postal` VARCHAR(10) NOT NULL,
  `localitat` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`botiga_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`empleat` (
  `empleat_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(60) NOT NULL,
  `cognoms` VARCHAR(100) NOT NULL,
  `nif` VARCHAR(20) NOT NULL,
  `telefon` VARCHAR(20) NOT NULL,
  `cargo` ENUM('cuiner', 'repartidor') NOT NULL,
  `botiga_botiga_id` INT NOT NULL,
  PRIMARY KEY (`empleat_id`),
  INDEX `fk_empleat_botiga1_idx` (`botiga_botiga_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleat_botiga1`
    FOREIGN KEY (`botiga_botiga_id`)
    REFERENCES `pizzeria`.`botiga` (`botiga_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda` (
  `comanda_id` INT NOT NULL AUTO_INCREMENT,
  `client_client_id` INT NOT NULL,
  `data_registre` DATETIME NOT NULL,
  `tipo` ENUM('domicili', 'recollir') NOT NULL,
  `repartidor_id` INT NULL,
  `data_lliurament` DATETIME NULL,
  INDEX `fk_comanda_client1_idx` (`client_client_id` ASC) VISIBLE,
  PRIMARY KEY (`comanda_id`),
  INDEX `fk_comanda_empleat1_idx` (`repartidor_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_client1`
    FOREIGN KEY (`client_client_id`)
    REFERENCES `pizzeria`.`client` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_empleat1`
    FOREIGN KEY (`repartidor_id`)
    REFERENCES `pizzeria`.`empleat` (`empleat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`categoria_pizza` (
  `categoria_pizza_id` INT NOT NULL,
  `nom` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`categoria_pizza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`producte` (
  `producte_id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `imatge` VARCHAR(128) NOT NULL,
  `preu` FLOAT NOT NULL,
  `tipo` ENUM('pizzes', 'hamburgueses', 'begudes') NOT NULL,
  `categoria_pizza_id` INT NULL,
  PRIMARY KEY (`producte_id`),
  INDEX `fk_producte_categoria1_idx` (`categoria_pizza_id` ASC) VISIBLE,
  CONSTRAINT `fk_producte_categoria_pizza1`
    FOREIGN KEY (`categoria_pizza_id`)
    REFERENCES `pizzeria`.`categoria_pizza` (`categoria_pizza_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizzeria`.`comanda_has_producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeria`.`comanda_has_producte` (
  `comanda_comanda_id` INT NOT NULL,
  `producte_producte_id` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`comanda_comanda_id`, `producte_producte_id`),
  INDEX `fk_comanda_has_producte_producte1_idx` (`producte_producte_id` ASC) VISIBLE,
  INDEX `fk_comanda_has_producte_comanda1_idx` (`comanda_comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_has_producte_comanda1`
    FOREIGN KEY (`comanda_comanda_id`)
    REFERENCES `pizzeria`.`comanda` (`comanda_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_has_producte_producte1`
    FOREIGN KEY (`producte_producte_id`)
    REFERENCES `pizzeria`.`producte` (`producte_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
